# Generated by Django 3.1.5 on 2021-09-04 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('first_paragraph', models.TextField()),
                ('body', models.TextField()),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='author.author')),
            ],
        ),
    ]
