version: '3.0'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_DB: "challenge"
    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    networks:
      - postgres-network
    depends_on:
      - db

  api:
    container_name: api
    build: ./medium/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./medium/:/usr/src/medium/
    depends_on:
      - db
    links:
      - db:db
    networks:
      - postgres-network
  
networks: 
  postgres-network:
    driver: bridge
