version: '3.0'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api_prod
    links:
      - api_prod:api_prod
    networks:
      - postgres_network_prod
    volumes:
      - static_volume:/usr/src/medium/static/
      
  db_prod:
    container_name: db_prod
    image: postgres:12
    ports:
      - "5433:5433"
    env_file:
      - .env
      - prod.env
    networks:
      - postgres_network_prod

  pgadmin_prod:
    container_name: pgadmin_prod
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "12345:80"
    networks:
      - postgres_network_prod
    depends_on:
      - db_prod

  api_prod:
    container_name: api_prod
    build: ./medium/
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn medium.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./medium/:/usr/src/medium/
      - static_volume:/usr/src/medium/static/
    depends_on:
      - db_prod
    links:
      - db_prod:db_prod
    networks:
      - postgres_network_prod
    env_file:
      - .env
      - prod.env
  
networks: 
  postgres_network_prod:
    driver: bridge

volumes:
  static_volume: