version: '3.0'
services:
  db_dev:
    container_name: db_dev
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
      - dev.env
    networks:
      - postgres_network_dev

  pgadmin_dev:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "16543:80"
    networks:
      - postgres_network_dev
    depends_on:
      - db_dev

  api_dev:
    container_name: api_dev
    build: ./medium/
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./medium/:/usr/src/medium/
    depends_on:
      - db_dev
    links:
      - db_dev:db_dev
    networks:
      - postgres_network_dev
    env_file:
      - .env
      - dev.env
  
networks: 
  postgres_network_dev:
    driver: bridge
