# Generated by Django 3.1.5 on 2021-09-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Author',
        ),
    ]
