# Generated by Django 3.1.5 on 2021-09-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210903_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
    ]
